import React, { useState } from 'react';
import { Layers, ArrowRight, ShieldCheck, CheckCircle2, Clock, Terminal } from 'lucide-react';

interface WorkViewProps {
  tasks: any[];
  onOpenTerminal: (agentId: string, runtimeType: string) => void;
}

export const WorkView: React.FC<WorkViewProps> = ({ tasks, onOpenTerminal }) => {
  const [filter, setFilter] = useState('all');

  const filteredTasks = tasks?.filter((t) => {
    if (filter === 'all') return true;
    return t.status === filter;
  });

  return (
    <div className="space-y-6 font-sans">
      {/* Task DAG Overview */}
      <div className="bg-slate-900 border border-slate-800/80 p-5 rounded-2xl flex justify-between items-center shadow-lg">
        <div>
          <h1 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <Layers className="w-5 h-5 text-indigo-400" />
            <span>Work Graph & Executable Task Board</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Visual task dependency tracking and autonomous verification pipeline
          </p>
        </div>

        <div className="flex gap-2">
          {['all', 'open', 'in_progress', 'done'].map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold uppercase font-mono transition cursor-pointer ${
                filter === f
                  ? 'bg-indigo-600 text-white'
                  : 'bg-slate-950 text-slate-400 border border-slate-800 hover:text-slate-200'
              }`}
            >
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* DAG Workflow Stages */}
      <div className="grid grid-cols-4 gap-4 text-xs font-mono">
        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl space-y-1">
          <div className="text-indigo-400 font-bold uppercase flex items-center gap-1.5">
            <Layers className="w-4 h-4" /> 1. Objective & Plan
          </div>
          <p className="text-slate-400 text-[11px] font-sans">Blueprint generated by Planner agent</p>
        </div>
        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl space-y-1">
          <div className="text-amber-400 font-bold uppercase flex items-center gap-1.5">
            <Terminal className="w-4 h-4" /> 2. Execution (PTY)
          </div>
          <p className="text-slate-400 text-[11px] font-sans">Worker agent running in Claude/Codex PTY</p>
        </div>
        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl space-y-1">
          <div className="text-emerald-400 font-bold uppercase flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4" /> 3. Machine Proof
          </div>
          <p className="text-slate-400 text-[11px] font-sans">Observed linter & test exit code checks</p>
        </div>
        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl space-y-1">
          <div className="text-blue-400 font-bold uppercase flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4" /> 4. Planner Review
          </div>
          <p className="text-slate-400 text-[11px] font-sans">Final requirement adjudication</p>
        </div>
      </div>

      {/* Tasks List */}
      <div className="bg-slate-900 border border-slate-800/80 p-5 rounded-2xl space-y-3">
        <h2 className="text-sm font-bold text-slate-200">Active Tasks ({filteredTasks?.length || 0})</h2>
        <div className="space-y-2.5">
          {filteredTasks?.map((t) => (
            <div
              key={t.id}
              className="p-4 bg-slate-950/60 border border-slate-800/80 rounded-xl flex items-center justify-between text-xs hover:border-slate-700 transition"
            >
              <div className="space-y-1.5 max-w-2xl">
                <div className="flex items-center gap-2">
                  <span className="font-mono font-bold text-indigo-400 bg-indigo-950/60 px-2 py-0.5 rounded border border-indigo-800/50">
                    {t.id}
                  </span>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded uppercase font-semibold bg-slate-800 text-slate-300">
                    Priority: {t.priority || 'medium'}
                  </span>
                </div>
                <div className="font-bold text-sm text-slate-100">{t.title}</div>
                {t.description && <p className="text-slate-400 font-sans text-xs line-clamp-2">{t.description}</p>}
              </div>

              <div className="flex items-center gap-3">
                <span className="text-[10px] uppercase font-bold text-amber-400 bg-amber-950/40 px-2.5 py-1 rounded border border-amber-800/50 font-mono">
                  {t.status || 'open'}
                </span>
                <button
                  onClick={() => onOpenTerminal(t.assignee_id || 'atlas', 'claude_code')}
                  className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-semibold transition cursor-pointer flex items-center gap-1.5"
                >
                  <Terminal className="w-3.5 h-3.5" />
                  <span>Launch PTY</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
